name: Chinese Text to Speech

on:
  push:
    branches:
      - main

jobs:
  run-script:
    name: Chinese Text to Speech
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
        AWS_CONFIG_FILE: ${{ github.workspace }}/aws-env.env
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to AWS, Set up environment
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION
        chmod +x ./chinese_script/generate_upload.sh

    - name: Generate speeches and upload to s3
      run: ./chinese_script/generate_upload.sh




