name: Text to Speech

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  run-script:
    name: Text to Speech
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::453685464323:role/githubb-action-pipeline
        aws-region: ap-southeast-2

#    - name: Configure AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      env:
#        AWS_CONFIG_FILE: ${{ github.workspace }}/aws-env.env
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ap-southeast-2

    - name: Login to AWS
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION

    - name: Set up environment
      run: chmod +x ./script/generate_upload.sh

    - name: Generate speeches and upload to s3
      run: ./script/generate_upload.sh
