name: Text to Speech

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  run-script:
    name: Text to Speech
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to AWS
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_REGION

    - name: Generate speeches
      run: sh /home/runner/work/audio/audio/script/generae_upload.sh
#
#    - name: Upload to s3
#      run: sh /home/runner/work/audio/audio/script/upload.sh
