name: Text to Speech

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  run-script:
    name: Text to Speech
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Set AWS Environment Variables
      run: |
        echo "AWS_DEFAULT_REGION=${{ steps.configure-aws.outputs.aws-region }}" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ steps.configure-aws.outputs.aws-access-key-id }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ steps.configure-aws.outputs.aws-secret-access-key }}" >> $GITHUB_ENV

    - name: Set up environment
      run: |
        chmod +x ./script/generate_upload.sh
        aws s3 sync s3://everyday-story .
        ls -R

#    - name: Generate speeches and upload to s3
#      run: ./script/generate_upload.sh
